import assert from 'node:assert/strict';
import { describe, it } from 'node:test';
import {
	formatRedirects,
	maxLedgerEntries,
	maxRedirectLineLength,
	parseLedger,
	unregisteredRemovals,
	unresolvableTargets,
	type LedgerEntry,
} from './ledger.ts';

/**
 * `redirects.json` is the redirect ledger: the single source of truth for URLs a human
 * moved or deleted (delivery.md §4.1). These cases pin the four CI gates of §4.2 —
 * schema (code domain / unique `from` / ceiling / line length), resolvable targets,
 * unregistered removals — plus the `_redirects` rendering the platform consumes.
 */

/** A schema-legal entry; overrides may be illegal on purpose (that is what the gate tests). */
const entry = (overrides: Record<string, unknown> = {}): LedgerEntry =>
	({
		from: '/docs/guides/kickoff/',
		to: '/docs/guides/minimal-agent/',
		code: 301,
		...overrides,
	}) as LedgerEntry;

const errorsFor = (value: unknown) => parseLedger(value).errors.join('\n');

describe('ledger schema gate (delivery.md §4.2.2)', () => {
	it('accepts the documented entry shape and keeps ledger order', () => {
		const first = entry({ from: '/docs/old/', to: '/docs/new/', code: 308 });
		const second = entry({ from: '/', to: '/docs/' });
		const { entries, errors } = parseLedger([first, { ...second, note: 'site root' }]);
		assert.deepEqual(errors, []);
		assert.deepEqual(
			entries.map((value) => value.from),
			['/docs/old/', '/'],
		);
		assert.equal(entries[0].code, 308);
	});

	it('rejects a code outside {301,302,307,308}', () => {
		for (const code of [303, 300, 200, '301', 301.5, null]) {
			assert.match(errorsFor([entry({ code })]), /`code`/, `code ${String(code)}`);
		}
	});

	it('requires the canonical trailing-slash form on both sides', () => {
		assert.match(errorsFor([entry({ from: '/docs/old' })]), /`from`/);
		assert.match(errorsFor([entry({ to: '/docs/new' })]), /`to`/);
		assert.match(
			errorsFor([entry({ from: '/docs/loop/', to: '/docs/loop/' })]),
			/redirects to itself/,
			'from === to is a loop',
		);
		assert.match(errorsFor([entry({ from: 'docs/old/' })]), /`from`/);
	});

	it('rejects query strings, fragments and whitespace in paths', () => {
		for (const from of ['/docs/old/?x=1', '/docs/old/#top', '/docs/old page/']) {
			assert.match(errorsFor([entry({ from })]), /`from`/, from);
		}
	});

	it('rejects duplicate `from` values', () => {
		assert.match(errorsFor([entry(), entry({ to: '/docs/other/' })]), /duplicate/);
	});

	it('rejects unknown keys, so typos surface instead of being ignored', () => {
		assert.match(errorsFor([{ ...entry(), status: 301 }]), /unknown key/);
		assert.match(errorsFor([{ from: '/a/', to: '/docs/' }]), /`code`/);
	});

	it('requires an absolute URL plus `external: true` for targets outside the site', () => {
		assert.match(errorsFor([entry({ to: 'https://oribos.dev/' })]), /external/);
		assert.match(
			errorsFor([entry({ to: '/docs/new/', external: true })]),
			/`to`/,
			'an external flag on an internal path is a contradiction',
		);
		assert.doesNotMatch(
			errorsFor([entry({ to: 'https://oribos.dev/why/', external: true })]),
			/./,
			'registered external target is schema-valid',
		);
		assert.match(
			errorsFor([entry({ to: 'ftp://oribos.dev/', external: true })]),
			/`to`/,
			'only http(s) leaves the site',
		);
	});

	it('rejects a ledger past the platform ceiling', () => {
		const legal = Array.from({ length: maxLedgerEntries - 1 }, (_, index) =>
			entry({ from: `/docs/old-${index}/`, to: '/docs/' }),
		);
		assert.deepEqual(parseLedger(legal).errors, [], `${legal.length} entries stay under the ceiling`);
		const pastTheCeiling = [...legal, entry({ from: '/docs/one-too-many/', to: '/docs/' })];
		assert.match(errorsFor(pastTheCeiling), /ceiling/);
	});

	it('rejects an entry whose rendered line reaches the platform line limit', () => {
		const long = `/docs/${'x'.repeat(maxRedirectLineLength)}/`;
		assert.match(errorsFor([entry({ to: long })]), /line|1,?000/i);
	});

	it('rejects non-arrays and non-object entries', () => {
		assert.match(errorsFor({}), /array/);
		assert.match(errorsFor([null]), /entry/);
		assert.match(errorsFor([entry(), 'nope']), /entry/);
	});
});

describe('_redirects rendering', () => {
	it('renders `from to code` lines in ledger order, with a generated-file header', () => {
		const rendered = formatRedirects([
			{ from: '/', to: '/docs/', code: 301 },
			{ from: '/docs/old/', to: '/docs/new/', code: 308, note: 'renamed' },
		]);
		assert.equal(
			rendered,
			[
				'# Generated by scripts/gen-redirects.mjs from redirects.json — do not edit.',
				'# The ledger is the single source of truth; order matters (first match wins).',
				'/ /docs/ 301',
				'/docs/old/ /docs/new/ 308',
				'',
			].join('\n'),
		);
	});

	it('is a pure function of the ledger: same input, same bytes', () => {
		const entries = [{ from: '/', to: '/docs/', code: 301 as const }];
		assert.equal(formatRedirects(entries), formatRedirects(entries));
	});
});

describe('target-resolvable gate (delivery.md §4.2.1)', () => {
	const pageRoutes = ['/docs/', '/docs/guides/minimal-agent/'];

	it('accepts a target that this version serves', () => {
		assert.deepEqual(unresolvableTargets([entry()], pageRoutes), []);
	});

	it('accepts a registered external target without resolving it locally', () => {
		const external = { from: '/docs/project/why-oribos/', to: 'https://oribos.dev/', code: 301 as const, external: true as const };
		assert.deepEqual(unresolvableTargets([external], pageRoutes), []);
	});

	it('flags a target that no page serves', () => {
		const issues = unresolvableTargets([entry({ to: '/docs/guides/deleted/' })], pageRoutes);
		assert.equal(issues.length, 1);
		assert.match(issues[0], /\/docs\/guides\/deleted\//);
	});
});

describe('unregistered-removal gate (delivery.md §4.2.3)', () => {
	const baseline = ['/docs/', '/docs/guides/kickoff/', '/docs/guides/minimal-agent/'];
	const current = ['/docs/', '/docs/guides/minimal-agent/'];

	it('flags a route that disappeared without a ledger entry', () => {
		const issues = unregisteredRemovals(baseline, current, []);
		assert.equal(issues.length, 1);
		assert.match(issues[0], /\/docs\/guides\/kickoff\//);
	});

	it('is satisfied once the removed route is registered', () => {
		const registered = [{ ...entry(), from: '/docs/guides/kickoff/' }];
		assert.deepEqual(unregisteredRemovals(baseline, current, registered), []);
	});

	it('ignores added routes', () => {
		assert.deepEqual(
			unregisteredRemovals(current, [...current, '/docs/guides/new/'], []),
			[],
		);
	});

	it('exempts the generated API tree namespace (ia.md §2 reserved, regenerated)', () => {
		// A symbol the framework stops exporting disappears from the tree; that is a
		// regeneration effect, not a URL a human moved, so the ledger is not involved.
		const withTree = [...baseline, '/docs/reference/api/agent/functions/oldSymbol/'];
		assert.deepEqual(unregisteredRemovals(withTree, current, []), [
			'/docs/guides/kickoff/ disappeared without a ledger entry — register it in redirects.json (delivery.md §4.2.3)',
		]);
	});
});
