/**
 * The redirect ledger — `redirects.json` is the single source of truth for URLs a human
 * changed (delivery.md §4.1), and `dist/_redirects` is generated from it. Pure rules
 * only; the CLI wrappers (`scripts/check-ledger.mjs`, `scripts/gen-redirects.mjs`) do
 * the filesystem and git plumbing.
 *
 * Gates (delivery.md §4.2, in the spec's order):
 *   1. every `to` resolves in this version's page set, or is a registered external link;
 *   2. the ledger is schema-legal — `code ∈ {301,302,307,308}`, unique `from`, under the
 *      platform ceiling, and every rendered line under the platform line limit;
 *   3. a route that disappeared between two versions is registered as a `from`;
 *   4. the ledger is the only place redirects are written (the generator guard lives in
 *      `scripts/gen-redirects.mjs --check`, because it compares generated bytes).
 */

/** Platform ceiling: 2,000 static + 100 dynamic rules (delivery.md §2.3). */
export const maxLedgerEntries = 2100;
/** Platform line limit for one `_redirects` rule (delivery.md §2.3). */
export const maxRedirectLineLength = 1000;

export const redirectCodes = [301, 302, 307, 308] as const;
export type RedirectCode = (typeof redirectCodes)[number];

export type LedgerEntry = {
	/** Source path, canonical trailing-slash form (delivery.md §4.3). */
	from: string;
	/** Target: a route this version serves, or a registered external URL. */
	to: string;
	code: RedirectCode;
	/** Why this entry exists — free text for the next reader. */
	note?: string;
	/** `to` leaves the site: the explicit registration §4.2.1 asks for. */
	external?: boolean;
};

export type ParsedLedger = { entries: LedgerEntry[]; errors: string[] };

const knownKeys = new Set(['from', 'to', 'code', 'note', 'external']);
const externalUrlPattern = /^https?:\/\/[^\s/]+(?:[/?#]\S*)?$/;
const canonicalPathPattern = /^\/(?:[^\s?#]*\/)?$/;

const isRecord = (value: unknown): value is Record<string, unknown> =>
	typeof value === 'object' && value !== null && !Array.isArray(value);

/**
 * The ledger line the platform will read: `[source] [destination] [code?]`, first match
 * wins (delivery.md §2.3). Order is ledger order, so the file is a pure function of the
 * ledger — that is what makes the generator idempotent (§4.2.4).
 */
export function renderLine(entry: LedgerEntry): string {
	return `${entry.from} ${entry.to} ${entry.code}`;
}

/** The whole `_redirects` file, header included. */
export function formatRedirects(entries: readonly LedgerEntry[]): string {
	return [
		'# Generated by scripts/gen-redirects.mjs from redirects.json — do not edit.',
		'# The ledger is the single source of truth; order matters (first match wins).',
		...entries.map(renderLine),
		'',
	].join('\n');
}

/** Gate 2: schema-legal ledger, with messages that name the entry. */
export function parseLedger(value: unknown): ParsedLedger {
	const errors: string[] = [];
	if (!Array.isArray(value)) {
		return { entries: [], errors: ['redirects.json must be an array of entries'] };
	}

	const entries: LedgerEntry[] = [];
	const seenFrom = new Map<string, number>();

	value.forEach((raw, index) => {
		const where = `entry ${index + 1}`;
		if (!isRecord(raw)) {
			errors.push(`${where}: every entry must be an object`);
			return;
		}

		const entryErrors: string[] = [];
		const unknown = Object.keys(raw).filter((key) => !knownKeys.has(key));
		if (unknown.length > 0) {
			entryErrors.push(`${where}: unknown key(s) ${unknown.join(', ')}`);
		}

		const { from, to, code, note, external } = raw;

		if (typeof from !== 'string' || !canonicalPathPattern.test(from)) {
			entryErrors.push(
				`${where}: \`from\` must be a site path in canonical trailing-slash form, got ${JSON.stringify(from)}`,
			);
		}

		const isExternal = external === true;
		if (external !== undefined && typeof external !== 'boolean') {
			entryErrors.push(`${where}: \`external\` must be a boolean`);
		} else if (isExternal) {
			if (typeof to !== 'string' || !externalUrlPattern.test(to)) {
				entryErrors.push(
					`${where}: an external \`to\` must be an absolute http(s) URL, got ${JSON.stringify(to)}`,
				);
			}
		} else if (typeof to !== 'string' || !canonicalPathPattern.test(to)) {
			entryErrors.push(
				`${where}: \`to\` must be a site path in canonical trailing-slash form, or an absolute URL registered with \`external: true\` (delivery.md §4.2.1), got ${JSON.stringify(to)}`,
			);
		}

		if (typeof code !== 'number' || !(redirectCodes as readonly number[]).includes(code)) {
			entryErrors.push(
				`${where}: \`code\` must be one of ${redirectCodes.join(' / ')}, got ${JSON.stringify(code)}`,
			);
		}

		if (note !== undefined && (typeof note !== 'string' || note.trim() === '')) {
			entryErrors.push(`${where}: \`note\` must be a non-empty string when present`);
		}

		if (entryErrors.length > 0) {
			errors.push(...entryErrors);
			return;
		}

		// The checks above have narrowed every field; the cast is the type-level half of them.
		const parsed = { from, to, code, note, external } as LedgerEntry;
		if (parsed.from === parsed.to) {
			errors.push(`${where}: \`from\` redirects to itself (${parsed.from})`);
			return;
		}
		if (renderLine(parsed).length >= maxRedirectLineLength) {
			errors.push(
				`${where}: rendered line reaches ${maxRedirectLineLength} characters (platform limit, delivery.md §2.3)`,
			);
			return;
		}

		const previous = seenFrom.get(parsed.from);
		if (previous !== undefined) {
			errors.push(`${where}: duplicate \`from\` ${parsed.from} (first seen in entry ${previous})`);
			return;
		}
		seenFrom.set(parsed.from, index + 1);
		entries.push(parsed);
	});

	if (value.length >= maxLedgerEntries) {
		errors.push(
			`redirects.json has ${value.length} entries — the platform ceiling is ${maxLedgerEntries} (delivery.md §4.2.2)`,
		);
	}

	return { entries, errors };
}

/** Gate 1: every internal `to` is served by this version's page set. */
export function unresolvableTargets(
	entries: readonly LedgerEntry[],
	pageRoutes: readonly string[],
): string[] {
	const served = new Set(pageRoutes);
	const issues: string[] = [];
	for (const entry of entries) {
		if (entry.external) continue;
		if (!served.has(entry.to)) {
			issues.push(
				`${entry.from} → ${entry.to}: no page serves \`${entry.to}\` in this version (delivery.md §4.2.1)`,
			);
		}
	}
	return issues;
}

/** Gate 3: routes removed since the baseline version must be registered as `from`. */
export function unregisteredRemovals(
	baselineRoutes: readonly string[],
	currentRoutes: readonly string[],
	entries: readonly LedgerEntry[],
): string[] {
	const current = new Set(currentRoutes);
	const registered = new Set(entries.map((entry) => entry.from));
	return baselineRoutes
		.filter((route) => !current.has(route) && !registered.has(route))
		.sort()
		.map(
			(route) =>
				`${route} disappeared without a ledger entry — register it in redirects.json (delivery.md §4.2.3)`,
		);
}
